apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: monitoring
data:
  grafana.ini: |
    [smtp]
    enabled = true
    host = smtp.gmail.com:587
    user = jokerbindass@gmail.com
    # If the password contains # or ; you have to wrap it with trippel quotes. Ex """#password;"""
    password = Kamal@89
    ;cert_file =
    ;key_file =
    skip_verify = true
    from_address = jokerbindass@gmail.com
    from_name = Grafana
    # EHLO identity in SMTP dialog (defaults to instance_name)
    ;ehlo_identity = dashboard.example.com


      
